spring.datasource.url=jdbc:sqlite:C:/Users/jamer/GitHub/UMGC-Comp-Sci/CMSC 495 Computer Science Capstone/cmsc495-expense-tracker-feature-unit-tests/expense_tracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC
